name: cdt/disaster-recovery

services:
  web:
    build:
      context: .
      dockerfile: appcontainer/Dockerfile
    image: cdt/disaster-recovery:web
    env_file: .env
    ports:
      - "${DJANGO_LOCAL_PORT:-8000}:8000"

  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: cdt/disaster-recovery:dev
    env_file: .env
    # https://code.visualstudio.com/docs/remote/create-dev-container#_use-docker-compose
    entrypoint: sleep infinity
    ports:
      - "${DJANGO_LOCAL_PORT:-8000}:8000"
    volumes:
      - ./:/cdt/app
