# Disable CI triggers for this pipeline
# It will be triggered "manually" from a GitHub Actions workflow
# https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/trigger?view=azure-pipelines#trigger-none
trigger: none

stages:
  - stage: terraform
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: environment
        variables:
          - name: OTHER_SOURCE
            value: $[variables['System.PullRequest.SourceBranch']]
          - name: INDIVIDUAL_SOURCE
            value: $[variables['Build.SourceBranchName']]
          - name: TARGET
            value: $[variables['System.PullRequest.TargetBranch']]
          - name: IS_TAG
            value: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]
        steps:
          - bash: python terraform/pipeline/workspace.py
            displayName: Set environment-related variables
            # save the values
            # https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-outputs-in-a-different-job
            name: env_select
            env:
              REASON: $(Build.Reason)
      - job: terraform
        dependsOn: environment
        variables:
          workspace: $[ dependencies.environment.outputs['env_select.workspace'] ]
        steps:
          - template: pipeline/deploy.yml
            parameters:
              service_connection: Production
              workspace: $(workspace)
