# Generated by Django 5.1.8 on 2025-04-21 21:02

import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VitalRecordsRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("started", "Started"),
                            ("eligibility_completed", "Eligibility Completed"),
                            ("submitted", "Request Submitted"),
                        ],
                        default="started",
                        max_length=50,
                    ),
                ),
                ("fire", models.CharField(choices=[("palisades", "Palisades fire"), ("eaton", "Eaton fire")], max_length=50)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
