# Generated by Django 5.2.3 on 2025-06-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="first_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="last_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="legal_attestation",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="middle_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="order_first_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="order_last_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="parent_1_first_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="parent_1_last_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="parent_2_first_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="parent_2_last_name",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
