# Generated by Django 5.2.4 on 2025-08-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vitalrecordsrequest",
            old_name="county_of_birth",
            new_name="county_of_event",
        ),
        migrations.RenameField(
            model_name="vitalrecordsrequest",
            old_name="date_of_birth",
            new_name="date_of_event",
        ),
        migrations.RenameField(
            model_name="vitalrecordsrequest",
            old_name="parent_1_first_name",
            new_name="person_1_first_name",
        ),
        migrations.RenameField(
            model_name="vitalrecordsrequest",
            old_name="parent_1_last_name",
            new_name="person_1_last_name",
        ),
        migrations.RenameField(
            model_name="vitalrecordsrequest",
            old_name="parent_2_first_name",
            new_name="person_2_first_name",
        ),
        migrations.RenameField(
            model_name="vitalrecordsrequest",
            old_name="parent_2_last_name",
            new_name="person_2_last_name",
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="person_1_birth_last_name",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="person_2_birth_last_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="type",
            field=models.CharField(
                choices=[("birth", "Birth record"), ("marriage", "Marriage record")], default="birth", max_length=10
            ),
            preserve_default=False,
        ),
    ]
