# Generated by Django 5.1.8 on 2025-04-22 03:34

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="legal_attestation",
            field=models.CharField(default="abc", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("self", "Self"),
                    ("parent", "Parent"),
                    ("legal guardian", "Legal guardian"),
                    ("child", "Child"),
                    ("grandparent", "Grandparent"),
                    ("grandchild", "Grandchild"),
                    ("sibling", "Sibling"),
                    ("spouse", "Spouse"),
                    ("domestic_partner", "Domestic partner"),
                ],
                default="self",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("started", "Started"),
                    ("eligibility_completed", "Eligibility Completed"),
                    ("statement_completed", "Sworn Statement Completed"),
                    ("submitted", "Request Submitted"),
                ],
                default="started",
                max_length=50,
            ),
        ),
    ]
