# Generated by Django 5.2.3 on 2025-06-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="address_2",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="address",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="city",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="email_address",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="zip_code",
            field=models.CharField(max_length=10),
        ),
    ]
