# Generated by Django 5.1.8 on 2025-04-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0002_vitalrecordsrequest_legal_attestation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="first_name",
            field=models.CharField(default="First", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="last_name",
            field=models.CharField(default="Last", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
