# Generated by Django 5.1.8 on 2025-04-23 22:25

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0002_vitalrecordsrequest_legal_attestation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="first_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("started", "Started"),
                    ("eligibility_completed", "Eligibility Completed"),
                    ("statement_completed", "Sworn Statement Completed"),
                    ("name_completed", "Name Completed"),
                    ("submitted", "Request Submitted"),
                ],
                default="started",
                max_length=50,
            ),
        ),
    ]
