# Generated by Django 5.2.4 on 2025-08-12 19:45

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0002_model_updates_marriage_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("initialized", "Initialized"),
                    ("started", "Started"),
                    ("type_completed", "Record Type Completed"),
                    ("statement_completed", "Sworn Statement Completed"),
                    ("name_completed", "Name Completed"),
                    ("county_completed", "County Completed"),
                    ("dob_completed", "Date of Birth Completed"),
                    ("parents_names_completed", "Parents Names Completed"),
                    ("order_info_completed", "Order Info Completed"),
                    ("submitted", "Request Submitted"),
                    ("enqueued", "Request Enqueued"),
                    ("packaged", "Request Packaged"),
                    ("sent", "Request Sent"),
                    ("finished", "Finished"),
                ],
                default="initialized",
                max_length=50,
            ),
        ),
    ]
