# Generated by Django 5.2.4 on 2025-08-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0003_alter_vitalrecordsrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="fire",
            field=models.CharField(
                choices=[
                    ("", "Select fire"),
                    ("eaton", "Eaton fire"),
                    ("hurst", "Hurst fire"),
                    ("lidia", "Lidia fire"),
                    ("palisades", "Palisades fire"),
                    ("woodley", "Woodley fire"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("", "Select relationship"),
                    ("self", "Self"),
                    ("parent", "Parent"),
                    ("legal guardian", "Legal guardian"),
                    ("child", "Child"),
                    ("grandparent", "Grandparent"),
                    ("grandchild", "Grandchild"),
                    ("sibling", "Sibling"),
                    ("spouse", "Spouse"),
                    ("domestic_partner", "Domestic partner"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequestmetadata",
            name="fire",
            field=models.CharField(
                choices=[
                    ("", "Select fire"),
                    ("eaton", "Eaton fire"),
                    ("hurst", "Hurst fire"),
                    ("lidia", "Lidia fire"),
                    ("palisades", "Palisades fire"),
                    ("woodley", "Woodley fire"),
                ],
                editable=False,
                max_length=50,
            ),
        ),
    ]
