# Generated by Django 5.2.4 on 2025-08-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0004_alter_vitalrecordsrequest_fire_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="person_1_middle_name",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="person_2_middle_name",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
