# Generated by Django 5.2.4 on 2025-08-26 22:24

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0005_vitalrecordsrequest_middle_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("initialized", "Initialized"),
                    ("started", "Started"),
                    ("submitted", "Request Submitted"),
                    ("enqueued", "Request Enqueued"),
                    ("packaged", "Request Packaged"),
                    ("sent", "Request Sent"),
                    ("finished", "Finished"),
                ],
                default="initialized",
                max_length=50,
            ),
        ),
    ]
