# Generated by Django 5.1.8 on 2025-04-24 23:40

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0005_vitalrecordsrequest_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="parent_1_first_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="parent_1_last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="parent_2_first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="parent_2_last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("started", "Started"),
                    ("eligibility_completed", "Eligibility Completed"),
                    ("statement_completed", "Sworn Statement Completed"),
                    ("name_completed", "Name Completed"),
                    ("county_completed", "County Completed"),
                    ("dob_completed", "Date of Birth Completed"),
                    ("parents_names_completed", "Parents Names Completed"),
                    ("submitted", "Request Submitted"),
                ],
                default="started",
                max_length=50,
            ),
        ),
    ]
