# Generated by Django 5.2.4 on 2025-09-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0006_alter_vitalrecordsrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="number_of_records",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6"), (7, "7"), (8, "8"), (9, "9"), (10, "10")],
                default=1,
                null=True,
            ),
        ),
    ]
