# Generated by Django 5.2.6 on 2025-09-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0007_alter_vitalrecordsrequest_number_of_records"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="county_of_event",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="fire",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="relationship",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="state",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="type",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequestmetadata",
            name="fire",
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
