# Generated by Django 5.2.6 on 2025-09-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0008_alter_vitalrecordsrequest_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="number_of_records",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequestmetadata",
            name="number_of_records",
            field=models.IntegerField(editable=False),
        ),
    ]
