# Generated by Django 5.1.8 on 2025-04-28 21:23

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0008_vitalrecordsrequest_enqueued_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("initialized", "Initialized"),
                    ("started", "Started"),
                    ("statement_completed", "Sworn Statement Completed"),
                    ("name_completed", "Name Completed"),
                    ("county_completed", "County Completed"),
                    ("dob_completed", "Date of Birth Completed"),
                    ("parents_names_completed", "Parents Names Completed"),
                    ("order_info_completed", "Order Info Completed"),
                    ("submitted", "Request Submitted"),
                    ("enqueued", "Request Enqueued"),
                    ("packaged", "Request Packaged"),
                    ("sent", "Request Sent"),
                    ("finished", "Finished"),
                ],
                default="initialized",
                max_length=50,
            ),
        ),
    ]
