# Generated by Django 5.2.6 on 2025-09-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0009_alter_vitalrecordsrequest_choices_number_of_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
