# Generated by Django 5.2.6 on 2025-09-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vital_records", "0010_vitalrecordsrequest_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalrecordsrequestmetadata",
            name="type",
            field=models.CharField(default="unknown", editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
