# Generated by Django 5.1.6 on 2025-03-03 23:34
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cdt_identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFlow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "label",
                    models.CharField(
                        help_text="A human readable label, used as the display text (user-facing)", max_length=50
                    ),
                ),
                (
                    "system_name",
                    models.SlugField(help_text="Internal system name for this flow, mapped to the root URL.", unique=True),
                ),
                ("urlconf_path", models.CharField(help_text="Django app path to the URLconf for this flow.", max_length=100)),
                (
                    "scopes",
                    models.CharField(
                        help_text="A space-separated list of identifiers used to specify what information is being requested",
                        max_length=200,
                    ),
                ),
                (
                    "eligibility_claim",
                    models.CharField(help_text="The claim that is used to verify eligibility", max_length=50),
                ),
                (
                    "extra_claims",
                    models.CharField(
                        blank=True, default="", help_text="A space-separated list of any additional claims", max_length=200
                    ),
                ),
                (
                    "redirect_failure",
                    models.CharField(
                        default="oauth:error",
                        help_text="A Django route in the form of app:endpoint to redirect to after a successful claims check",
                        max_length=50,
                    ),
                ),
                (
                    "redirect_success",
                    models.CharField(
                        default="oauth:success",
                        help_text="A Django route in the form of app:endpoint to redirect to after a successful claims check",
                        max_length=50,
                    ),
                ),
                (
                    "scheme_override",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="(Optional) the authentication scheme to use. Defaults to that provided by the OAuth config.",  # noqa: E501
                        max_length=50,
                        verbose_name="Claims scheme",
                    ),
                ),
                (
                    "oauth_config",
                    models.ForeignKey(
                        help_text="The IdG connection details for this flow.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cdt_identity.identitygatewayconfig",
                    ),
                ),
            ],
        ),
    ]
