# Generated by Django 5.1.6 on 2025-03-05 00:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cdt_identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFlow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "system_name",
                    models.SlugField(help_text="Internal system name for this flow.", unique=True),
                ),
                (
                    "claims_request",
                    models.ForeignKey(
                        help_text="The claims request details for this flow.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cdt_identity.claimsverificationrequest",
                    ),
                ),
                (
                    "oauth_config",
                    models.ForeignKey(
                        help_text="The IdG connection details for this flow.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cdt_identity.identitygatewayconfig",
                    ),
                ),
            ],
        ),
    ]
