# Generated by Django 5.1.6 on 2025-03-03 23:58
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cdt_identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFlow",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "label",
                    models.CharField(
                        help_text="A human readable label, used as the display text (user-facing)", max_length=50
                    ),
                ),
                (
                    "system_name",
                    models.SlugField(help_text="Internal system name for this flow, mapped to the root URL.", unique=True),
                ),
                ("urlconf_path", models.CharField(help_text="Django app path to the URLconf for this flow.", max_length=100)),
                (
                    "claims_request",
                    models.ForeignKey(
                        help_text="The claims request details for this flow.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cdt_identity.claimsverificationrequest",
                    ),
                ),
                (
                    "oauth_config",
                    models.ForeignKey(
                        help_text="The IdG connection details for this flow.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cdt_identity.identitygatewayconfig",
                    ),
                ),
            ],
        ),
    ]
