# Generated by Django 5.1.8 on 2025-04-17 03:19

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VitalRecordsRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("started", "Started"),
                            ("eligibility_completed", "Eligibility Completed"),
                            ("sworn_statement_completed", "Sworn Statement Completed"),
                            ("submitted", "Request Submitted"),
                        ],
                        default="started",
                        max_length=50,
                    ),
                ),
                ("fire", models.CharField(choices=[("palisades", "Palisades fire"), ("eaton", "Eaton fire")], max_length=50)),
            ],
        ),
    ]
