# Generated by Django 5.1.8 on 2025-04-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_vitalrecordsrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="legal_attestation",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("self", "Self"),
                    ("parent", "Parent"),
                    ("legal guardian", "Legal guardian"),
                    ("child", "Child"),
                    ("grandparent", "Grandparent"),
                    ("grandchild", "Grandchild"),
                    ("sibling", "Sibling"),
                    ("spouse", "Spouse"),
                    ("domestic_partner", "Domestic partner"),
                ],
                default="self",
                max_length=50,
            ),
        ),
    ]
