# Generated by Django 5.1.8 on 2025-04-18 00:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_vitalrecordsrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
