# Generated by Django 5.1.8 on 2025-04-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_vitalrecordsrequest_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
