# Generated by Django 5.1.8 on 2025-04-17 07:07

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_vitalrecordsrequest_legal_attestation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vitalrecordsrequest",
            name="relationship",
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="fire",
            field=models.CharField(
                blank=True, choices=[("palisades", "Palisades fire"), ("eaton", "Eaton fire")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="legal_attestation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("started", "Started"),
                    ("eligibility_completed", "Eligibility Completed"),
                    ("sworn_statement_completed", "Sworn Statement Completed"),
                    ("name_completed", "Name Completed"),
                    ("submitted", "Request Submitted"),
                ],
                default="started",
                max_length=50,
            ),
        ),
    ]
