# Generated by Django 5.1.8 on 2025-04-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_vitalrecordsrequest_relationship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalrecordsrequest",
            name="relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("self", "Self"),
                    ("parent", "Parent"),
                    ("legal guardian", "Legal guardian"),
                    ("child", "Child"),
                    ("grandparent", "Grandparent"),
                    ("grandchild", "Grandchild"),
                    ("sibling", "Sibling"),
                    ("spouse", "Spouse"),
                    ("domestic_partner", "Domestic partner"),
                ],
                max_length=50,
            ),
        ),
    ]
