# Generated by Django 5.1.8 on 2025-04-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_vitalrecordsrequest_relationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="fire",
            field=models.CharField(choices=[("palisades", "Palisades fire"), ("eaton", "Eaton fire")], max_length=50),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="legal_attestation",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="vitalrecordsrequest",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("self", "Self"),
                    ("parent", "Parent"),
                    ("legal guardian", "Legal guardian"),
                    ("child", "Child"),
                    ("grandparent", "Grandparent"),
                    ("grandchild", "Grandchild"),
                    ("sibling", "Sibling"),
                    ("spouse", "Spouse"),
                    ("domestic_partner", "Domestic partner"),
                ],
                max_length=50,
            ),
        ),
    ]
