# Generated by Django 5.1.4 on 2025-01-23 03:51

import uuid

from django.db import migrations, models

import web.oauth.models.secret_name_field
import web.oauth.secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("client_name", models.SlugField(help_text="The name of this OAuth client", unique=True)),
                (
                    "client_id_secret_name",
                    web.oauth.models.secret_name_field.SecretNameField(
                        help_text="The name of the secret containing the client ID for this OAuth client",
                        max_length=127,
                        validators=[web.oauth.secrets.SecretNameValidator()],
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        help_text="The fully qualified HTTPS domain name for an OAuth authority server", max_length=50
                    ),
                ),
                (
                    "scheme",
                    models.CharField(help_text="The authentication scheme for the authority server", max_length=50),
                ),
            ],
            options={
                "verbose_name": "OAuth Client",
            },
        ),
    ]
