# Generated by Django 5.1.4 on 2025-01-23 03:51

import uuid
import web.core.models
import web.secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="oauthclientconfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("client_name", models.CharField(help_text="The name of this OAuth client", max_length=50)),
                (
                    "client_id_secret_name",
                    web.core.models.SecretNameField(
                        help_text="The name of the secret containing the client ID for this OAuth client",
                        max_length=127,
                        validators=[web.secrets.SecretNameValidator()],
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        help_text="The fully qualified HTTPS domain name for an OAuth authority server", max_length=50
                    ),
                ),
                (
                    "scheme",
                    models.CharField(help_text="The authentication scheme to use for this OAuth client", max_length=50),
                ),
                (
                    "scopes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="A space-separated list of identifiers used to specify what access privileges are being requested",  # noqa: E501
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="oauthclientconfig",
            options={"verbose_name": "OAuth Client"},
        ),
    ]
