name: Publish docs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/mkdocs.yml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/mkdocs.yml"
      - "docs/**"
      - ".markdownlint.yaml"
      - "mkdocs.yml"

jobs:
  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    # don't publish for pull requests
    if: github.event.pull_request == null
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: .github/workflows/.python-version
          cache: pip
          cache-dependency-path: |
            "**/pyproject.toml"
            "docs/requirements.txt"

      - name: Install MkDocs requirements
        run: |
          pip install -r docs/requirements.txt

      - name: Deploy MkDocs website
        run: |
          mkdocs gh-deploy --force
